[sqf.command_case]
severity = "Error"
options.ignore = [
    "AGLtoASL",
    "ASLtoAGL",
    "WEST",
    "EAST",
    "INDEPENDENT",
    "RESISTANCE",
    "CIVILIAN",
    "getVehicleTiPars",
    "setVehicleTiPars",
]

[sqf.banned_commands]
options.banned = [
    "execVM",
]
