
name = "ArmaForces Mods"
mainprefix = "z"
prefix = "afm"

[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md",
    "armaforces_mods_x64.dll",
]

exclude = ["*.psd", "*.png", "*.tga"]

[properties]
author = "ArmaForces"

[version]
path = "addons/main/script_version.hpp"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3
    "2369477168", # ADT
]
parameters = [
    "-debug",
    "-filePatching",
    "-name=dev",
    "-noSplash",
    "-showScriptErrors",
    "-window",
]
