
name = "ArmaForces Mods"
mainprefix = "z"
prefix = "afm"

[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md",
    "armaforces_mods_x64.dll",
]

exclude = ["*.psd", "*.png", "*.tga"]

[properties]
author = "ArmaForces"

[version]
path = "addons/main/script_version.hpp"

# Unused in HEMTT v1.11 or higher, kept for backwards compatibility
[asc]
exclude = [
    ".inc.sqf",
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "2369477168", # ADT
]
parameters = [
    "-name=dev",
    "-window",
]

[hemtt.launch.ace]
extends = "default"
workshop = [
    "463939057", # ACE
#    "766491311", # KKA3 ACE Extension
]

[hemtt.launch.cup]
extends = "default"
workshop = [
    "583496184", # CUP Terrains - Core
    "583544987", # CUP Terrains - Maps
]

[hemtt.launch.vn]
extends = "default"
dlc = [
    "S.O.G. Prairie Fire",
]

[hemtt.launch.ww2]
extends = "default"
dlc = [
    "Spearhead 1944",
]

[hemtt.launch.gm]
extends = "default"
dlc = [
    "Global Mobilization",
]
