#define CREATE_BROKEN_GOGGLES(ORIGINAL_NVG) class ORIGINAL_NVG; \
class GVAR(DOUBLES(ORIGINAL_NVG,Broken)) : ORIGINAL_NVG { \
        scope = 1; \
        visionMode[] = {"Normal"} \
}

class CfgWeapons {
    CREATE_BROKEN_GOGGLES(ACE_NVG_Gen1);
    CREATE_BROKEN_GOGGLES(ACE_NVG_Gen2);
    CREATE_BROKEN_GOGGLES(ACE_NVG_Gen4);
    CREATE_BROKEN_GOGGLES(ACE_NVG_Wide);
    CREATE_BROKEN_GOGGLES(NVGoggles);
    CREATE_BROKEN_GOGGLES(NVGoggles_INDEP);
    CREATE_BROKEN_GOGGLES(NVGoggles_OPFOR);
    CREATE_BROKEN_GOGGLES(NVGoggles_tna_F);
    CREATE_BROKEN_GOGGLES(NVGogglesB_blk_F);
    CREATE_BROKEN_GOGGLES(NVGogglesB_gry_F);
    CREATE_BROKEN_GOGGLES(O_NVGoggles_ghex_F);
    CREATE_BROKEN_GOGGLES(O_NVGoggles_grn_F);
    CREATE_BROKEN_GOGGLES(O_NVGoggles_hex_F);
    CREATE_BROKEN_GOGGLES(O_NVGoggles_urb_F);
};
