name: Arma

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Return Types
      run: python3 tools/return_checker.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT build
      run: hemtt build

  build:
    runs-on: windows-2022
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Pull Arma3Tools
      run: |
        echo ${{ secrets.CR_PAT }} | docker login -u ${{ secrets.CR_USER }} --password-stdin ghcr.io
        docker pull ghcr.io/armaforces/arma3tools:v2
    - name: Build using HEMTT
      run: |
        docker run -v "$(pwd):c:/workdir" -e CI=$True ghcr.io/armaforces/arma3tools:v2 hemtt release

    - uses: actions/upload-artifact@v4
      with:
        name: armaforces_mods
        path: |
            releases/*.zip
            !releases/afm-latest.zip
