name: Rust Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rustfmt
      run: cd extension && cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clippy
      run: |
        rustup -q component add clippy
        cd extension && cargo clippy --all-features -- -D warnings
